GRANT SELECT ON artists TO "DDEXTER";
GRANT SELECT ON artists TO "SKULTHUM.RASHID";
GRANT SELECT ON artists TO "CARLO.QUICK";

GRANT SELECT ON tracks TO "DDEXTER";
GRANT SELECT ON tracks TO "SKULTHUM.RASHID";
GRANT SELECT ON tracks TO "CARLO.QUICK";

GRANT SELECT ON artist_to_tracks TO "DDEXTER";
GRANT SELECT ON artist_to_tracks TO "SKULTHUM.RASHID";
GRANT SELECT ON artist_to_tracks TO "CARLO.QUICK";

GRANT SELECT ON artist_to_genres TO "DDEXTER";
GRANT SELECT ON artist_to_genres TO "SKULTHUM.RASHID";
GRANT SELECT ON artist_to_genres TO "CARLO.QUICK";

GRANT SELECT ON countries TO "DDEXTER";
GRANT SELECT ON countries TO "SKULTHUM.RASHID";
GRANT SELECT ON countries TO "CARLO.QUICK";

GRANT SELECT ON country_to_code TO "DDEXTER";
GRANT SELECT ON country_to_code TO "SKULTHUM.RASHID";
GRANT SELECT ON country_to_code TO "CARLO.QUICK";