GRANT SELECT ON artists TO  "DDEXTER", "CARLO.QUICK", "SKULTHUM.RASHID";
GRANT SELECT, REFERENCES ON tracks TO  "DDEXTER", "CARLO.QUICK", "SKULTHUM.RASHID";
GRANT SELECT ON artist_to_tracks TO "DDEXTER", "CARLO.QUICK", "SKULTHUM.RASHID";
GRANT SELECT ON artist_to_genres TO  "DDEXTER", "CARLO.QUICK", "SKULTHUM.RASHID";
GRANT SELECT ON countries TO  "DDEXTER", "CARLO.QUICK", "SKULTHUM.RASHID";
GRANT SELECT, REFERENCES ON country_to_code TO "DDEXTER", "CARLO.QUICK", "SKULTHUM.RASHID";

GRANT SELECT ON track_to_countries TO "DDEXTER", "CARLO.QUICK", "SKULTHUM.RASHID";