DROP TABLE artists CASCADE CONSTRAINTS;
DROP TABLE tracks CASCADE CONSTRAINTS;
DROP TABLE artist_to_tracks CASCADE CONSTRAINTS;
DROP TABLE artist_to_genres CASCADE CONSTRAINTS;

DROP TABLE countries CASCADE CONSTRAINTS;
DROP TABLE country_to_code CASCADE CONSTRAINTS;
